production:
  adapter: postgresql
  encoding: unicode
  database: appthat_development
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  encoding: unicode
  database: appthat_development
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  encoding: unicode
  database: appthat_test
  pool: 5
  timeout: 5000
